% RPF_guide_counts
%
% Description of the counts struct used in the RPF toolbox. 
% 
% counts is a struct whose fields contain counts of the number of trials in
% a data set where certain responses were given under certain conditions,
% as discussed below. These response counts are used for MLE fitting of d'
% and meta-d', as well as for constructing type 2 ROC curves from which
% type 2 AUC is computed. The counts struct is generated by
% RPF_trials2counts_SDT.
%
% counts contains the following fields:
% 
% counts.task_type 
%   - a string denoting what type of task was employed in trialData
%   - 'detect x' denotes a task in which all trials where stimulus strength 
%     x takes on its minimal value have a stimID of 0, and all trials where 
%     x is larger than the minimal value have a stimID of 1. in such cases, 
%     the task is to detect whether x exceeds its minimal value or not. for 
%     instance, if x is grating contrast, the task might be to detect when 
%     a grating is present (i.e. when grating contrast > 0).
%   - 'discriminate at x' denotes all other kinds of tasks, in which stimID
%     is assumed to take on values of 0 or 1 at each level of x. in such
%     cases, the task is to discriminate some stimulus feature that can
%     take on one of two values at any level of x. for instance, if x is
%     grating contrast, the task might be to discriminate whether the
%     grating is tilting left or right.
%   - the value of counts.task_type has consequences for how the fields
%     below are organized.
%
% counts.nR_S1 and counts.nR_S2
%   - these contain counts of how many times the subject gave each possible 
%     resonse and rating for S1 and S2 stimuli, respectively, at each level 
%     of x
%   - each has nRatings*2 columns, where column number codes for response
%     and rating by starting from the highest possible rating for "S1"
%     responses and descending to successively lower ratings, and then
%     ascending from the lowest to the highest possible ratings for "S2"
%     responses. 
%
%     for instance, suppose the rating scale has 3 levels, i.e. nRatings = 3.
%     then the column numbers of nR_S1 and nR_S2 code for
%
%          1           2           3          4           5           6     
%     ("S1", 3)   ("S1", 2)   ("S1", 1)   ("S2", 1)   ("S2", 2)   ("S2", 3)
%
%     where e.g. ("S1", 3) refers to trials where the response was "S1" and
%     the rating was 3.
%   - the rows of nR_S1 and nR_S2 code for levels of stimulus strength x, 
%     where the number of rows for each depends on counts.task_type
%   - if task_type = 'detect x', then S1 stimuli only occur at one level of
%     x (where x is minimal) and S2 stimuli occur at the remaining levels
%     of x. thus, nR_S1 has one row, and nR_S2 has (nx-1) rows where nx is
%     the number of levels of x. rows are organized in ascending levels of
%     x, so that the largest row number indicates the highest level of x.
%   - if task_type = 'discriminate at x', then S1 and S2 stimuli occur at
%     every level of x. thus, nR_S1 and nR_S2 both have nx rows, where nx
%     is the number of levels of x. rows are organized in ascending levels of
%     x, so that the largest row number indicates the highest level of x.
%   - so, for example, if the task type is 'discriminate at x', nRatings = 4, 
%     and nx = 10, then nR_S2(10, 6) tells you how many times the subject 
%     responded "S2" with a rating of 2 when the stimulus was S2 and x had 
%     its highest value.
%   - NOTE: some experimental designs may contain cases where a
%     discrimination task is used (e.g. discriminate left vs right grating
%     tilt), while also containing some trials where the stimulus is absent
%     and so there is no objective way to assign stimulus identity (e.g.
%     trials where contrast = 0 and so no grating is physically presented,
%     and so no grating tilt can be assigned). such trials cannot be
%     entered into an SDT analysis since that requires being able to assign
%     an objective stimulus ID. thus, such trials are automatically
%     excluded from SDT analysis by the RPF toolbox. in such cases, the number
%     of rows of nR_S1 and nR_S2 will be (nx-1) rather than nx, since the
%     stimulus-absent trials are omitted from analysis. see RPF_guide('info') 
%     and RPF_guide('trialData') for further considerations on how to approach 
%     such cases. 
%
% counts.nC_rS1 and counts.nI_rS1
%   - these contain counts of how many times the subject gave each possible 
%     rating for "S1" responses when that "S1" response was correct (nC_rS1) 
%     or incorrect (nI_rS1) at each level of x
%   - each has nRatings columns, where column number codes for rating in
%     ascending order. 
%
%     for instance, suppose the rating scale has 3 levels, i.e. nRatings = 3.
%     then the column numbers of nC_rS1 and nI_rS1 code for
%
%           1             2              3     
%     (rating = 1)   (rating = 2)   (rating = 3)  
%
%   - the rows of nC_rS1 and nI_rS1 code for levels of stimulus strength x, 
%     where the number of rows for each depends on counts.task_type
%   - if task_type = 'detect x', then S1 stimuli only occur at one level of
%     x (where x is minimal) and S2 stimuli occur at the remaining levels
%     of x. correct "S1" responses occur when the stimulus is S1, and so
%     nC_rS1 has only one row. incorrect "S1" responses occur when the
%     stimulus is S2, and so nI_rS1 has (nx-1) rows where nx is
%     the number of levels of x. rows are organized in ascending levels of
%     x, so that the largest row number indicates the highest level of x.
%   - if task_type = 'discriminate at x', then S1 and S2 stimuli occur at
%     every level of x. thus, nC_rS1 and nI_rS1 both have nx rows, where nx
%     is the number of levels of x. rows are organized in ascending levels of
%     x, so that the largest row number indicates the highest level of x.
%   - so, for example, if the task type is 'discriminate at x', nRatings = 4, 
%     and nx = 10, then nC_rS1(10, 3) tells you how many times the subject 
%     gave a correct "S1" response with a rating of 3 when x had 
%     its highest value.
%   - NOTE: the same caveat about the number of rows in 'discriminate at x'
%     tasks as discussed for nR_S1 and nR_S2 applies here as well.
%
% counts.nC_rS2 and counts.nI_rS2
%   - these contain counts of how many times the subject gave each possible 
%     rating for "S2" responses when that "S2" response was correct (nC_rS2) 
%     or incorrect (nI_rS2) at each level of x
%   - all considerations for these fields are analogous to those for nC_rS1
%     and nI_rS1 discussed above, with the following exception:
%   - if task_type = 'detect x', then S1 stimuli only occur at one level of
%     x (where x is minimal) and S2 stimuli occur at the remaining levels
%     of x. incorrect "S2" responses occur when the stimulus is S1, and so
%     nI_rS2 has only one row. correct "S2" responses occur when the
%     stimulus is S2, and so nC_rS2 has (nx-1) rows where nx is
%     the number of levels of x. rows are organized in ascending levels of
%     x, so that the largest row number indicates the highest level of x.
